### ISSUE TITLE
WDI-BOS-04: Post refactoring commits here

### ISSUE THREAD

**Issue by digitalcora** [ga-wdi-boston/wdi_10_design_patterns_refactoring#1]
Link to each of your three commented commits!

**Comment by brian-penguin** [comment]
https://github.com/brimatteng/evening_for_us/commit/13227fd85b0a69781ed0d5ff7c237b48040a9da9
https://github.com/brimatteng/evening_for_us/commit/d31f775554e6f509e5e2837ec3f3f0ee2dcf8e87
https://github.com/brimatteng/evening_for_us/commit/d10bbe4a9e911fc3e70588835bb4d2c48af0ab17
https://github.com/brimatteng/evening_for_us/commit/fa29c4cf5f00966708920bcaf87202361eef99b2

**Comment by csb324** [comment]
https://github.com/csb324/HangAtBrown/commit/c8769407104640cb7351449ae695c7db670e8758 
https://github.com/csb324/HangAtBrown/commit/4f39e94aa18c6264203d8be57a34b43e4ceba8b0
https://github.com/csb324/HangAtBrown/commit/65134871d1165bff52ee674327daebea872efa60 

refactoring like whaaat

**Comment by kaaterskil** [comment]
https://github.com/kaaterskil/bobsbagels/commit/7fe5f00c7ff83b17729f536c9dad08a82e683a3d
Did a bunch of methods

**Comment by emmagard** [comment]
(UncommunicativeVariableName)
https://github.com/zhbanton/photo_mixer/commit/2f99f3152a0efb98ee70232c3d5b144fe968b57c
(removed unused methods)
https://github.com/zhbanton/photo_mixer/commit/af013d59ca6d739162d73c3955f14042dc5ae031
(UncommunicativeVariableName)
https://github.com/zhbanton/photo_mixer/commit/4b833388770e083f8ef12890ee2e080577642e01

**Comment by katrynmc** [comment]
https://github.com/testkitschen/recollektion/commit/c9427f87c76e911abf630d829bbc0be33410c7e1

**Comment by maxkohl88** [comment]
Moved a beastly method from a controller into the appropriate model
https://github.com/maxkohl88/fantasy_history_2.0/commit/c292f084d1473f7d2b490039af5aaabdaaa2a691

Removed some completely useless/unused code
https://github.com/maxkohl88/fantasy_history_2.0/commit/bdcfa01154c7da05201ba26318246fdcc0fe84e2

**Comment by devindreszer** [comment]
Two in 1:
https://github.com/devindreszer/rescue_dogs/commit/32a8f207b3120960a9b51aa000bcf41b53075645
https://github.com/devindreszer/bagel_store/commit/bacf6d33e9e57541477c858e129dcb283ee3be22

**Comment by krk324** [comment]
https://github.com/krk324/supworld/commit/332345f0eb392ef048935c7d84b8173fa0cb0f14
https://github.com/krk324/supworld/commit/b800f338fb94f0ff7a108a0740b87dfddac1d048

**Comment by zhbanton** [comment]
https://github.com/zhbanton/conehead/commit/9bbe77653eb37e490982695913d1ab6760d727a6

starting reworking the models and it got kinda hairy so only did the one

**Comment by nnovak13** [comment]
https://github.com/nnovak13/politicstest/commit/2cc2e6f52b52121a14b194bce2bfed8d92d0ed56

**Comment by dmcgann1** [comment]
https://github.com/kaaterskil/bobsbagels/commit/be5fe13d2e8ceb68f039dd50bcf98006a2161be7#diff-d41d8cd98f00b204e9800998ecf8427e
https://github.com/kaaterskil/bobsbagels/commit/210bc4b23fe80a819849c3ef12905e9d49b9e72a#diff-d41d8cd98f00b204e9800998ecf8427e

**Comment by EricRho** [comment]
Derp... Attempt refactoring matcher scoring
https://github.com/csb324/getdated/commit/876de52aa5a7ec85019f120f951636f50e3f662f#diff-d41d8cd98f00b204e9800998ecf8427e

**Comment by afeinber** [comment]
https://github.com/afeinber/akk/commit/6c513b0681798c245b5e40c9546ae3484bd7c4f7
https://github.com/afeinber/akk/commit/7f772ac1dd17918828bf04b2a7f4d3c873e7c2ff
